### PR TITLE
query parameter shortcode

### PR DESCRIPTION
**Pull request by ChristofLee**
Add shortcode to display a query string on a page.

The shortcode:
Screenshot 2021-10-16 at 10 22 31

Test URL:
https://shortcodes-wp.local/sample-page/?test=Chistof+Lee

Result:
Screenshot 2021-10-16 at 10 22 15

### CODE REVIEW

**Comment by warengonzaga** [comment]
Hi @ChristofLee I guess instead of ``[wpuser_query_string]`` let's change it to ``[wpinfo_query_param]`` for query parameters.

**Comment by ChristofLee** [comment]
Understood. Will do this when I can.

**Comment by ChristofLee** [comment]
Updated as requested.

**Review by warengonzaga — APPROVED** [review]
This is good for me @ChristofLee good work!

**Pull request merged**
